### ISSUE TITLE
wrong font set on Gimp appimage

### ISSUE THREAD

**Issue by TasMania17** [ivan-hc/GIMP-x86_64.AppImage#1]
Very powerful script Ivan. It works, unfortunately I have the wrong font set so cannot use it. Using Ubuntu 22.04

![GimpAppimageScreenshot](https://user-images.githubusercontent.com/32868462/155432129-e79d0ec0-280b-4ff0-bce5-f1ca22f1f59f.png)

**Comment by ivan-hc** [comment]
hi, I've shown the solution to another user on Reddit https://www.reddit.com/r/archlinux/comments/svz331/arch_deployer_first_release/hxjxd7h/?context=3 you should aedit the AppRun during the process by adding some missing lines.
I have faced the same issue with a script that creates GIMP from Debian Unstable time ago, here is the script https://github.com/ivan-hc/AM-application-manager/blob/main/programs/x86_64/gimp you may be interested to the lines from 57 to 64, ie:

    export GIMP2_DATADIR="${HERE}"/usr/share/gimp/2.0/
    export GIMP2_SYSCONFDIR="${HERE}"/usr/etc/gimp/2.0/
    export GIMP2_PLUGINDIR="${HERE}"/usr/lib/gimp/2.0/
    export GIMP3_DATADIR="${HERE}"/usr/share/gimp/2.99/
    export GIMP3_SYSCONFDIR="${HERE}"/usr/etc/gimp/2.99/
    export GIMP3_PLUGINDIR="${HERE}"/usr/lib/gimp/2.99/
    export GEGL_PATH="${HERE}"/usr/lib/x86_64-linux-gnu/gegl-0.4/
    export BABL_PATH="${HERE}"/usr/lib/x86_64-linux-gnu/babl-0.1/

these lines should work well with the developer edition too. If you have problems, try to comment the last line related to "BABL". Just follow the error messages when you launch the AppRun from your another terminal's window.

**Comment by ivan-hc** [comment]
PS: sorry, maybe this is a problem of the fonts available on the host. Have you installed `ttf-mscorefonts-installer` or `fonts-freefont-ttf` or `fonts-unifont` or `fonts-unifont-extra` or `fonts-noto` or `fonts-lato`?

**Comment by TasMania17** [comment]
I can't solve this. I noticed the deb files loaded by the original text file 'gimp' have changed.
(sources:     - deb http://ftp.debian.org/debian/ sid main contrib non-free
They are listed as: gimp gimp-data gimp-data-extras gimp-help-common
I think they are now: gimp gimp-data libgimp2.0 libgimp2.0-dev libgimp2.0-doc
I checked the debs here:
http://archive.ubuntu.com/ubuntu/pool/universe/g/gimp/

**Comment by ivan-hc** [comment]
No, this is not related to the dependences into the AppImage, this is an issue of the AppRun.

Extract the AppImage this way:

    GNU_Image_Manipulation_Program-x86_64.AppImage --appimage-extract

Try to add this line to the AppRun:

    if [ -e /etc/fonts/fonts.conf ]; then
       export FONTCONFIG_PATH=/etc/fonts
    fi

and test the changes by running the AppRun.

**Comment by ivan-hc** [comment]
Just bundled a new AppImage from using this PPA as source: https://launchpad.net/~savoury1

I have tested it on Ubuntu 18.04 and Debian Testing/Unstable and worked great for me!

There should not be problems in executing this AppImage, however in case of problems, run the AppImage from the shell and read the output.

Let me know.

**Comment by TasMania17** [comment]
Thanks Ivan. Appimage works perfectly on Ubuntu 22.04. Good luck with your projects :)
